version: "3.8"
services:
  app:
    build:
      args:
        user: quangnd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: skp
    container_name: skp-app
    restart: unless-stopped
    working_dir: /var/www/laravel-shopify-app
    volumes:
      - ./:/var/www/laravel-shopify-app
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: skp-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - .docker/data/db:/var/lib/mysql/
    networks:
      - db-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${ADMINER_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db-network



  nginx:
    image: nginx:alpine
    container_name: skp-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/laravel-shopify-app
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/shopify-default.conf
    networks:
      - app-network

  npm:  
    image: node:18-alpine
    working_dir: /var/www/laravel-shopify-app
  
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - .docker/data/redis:/data
    restart: always
    networks:
      - queue-network
networks:
  app-network:
    driver: bridge
  queue-network:
    driver: bridge
  db-network:
    driver: bridge