version: "3.8"
services:
  app:
    build:
      args:
        user: quangnd
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: skp
    container_name: shopify-app
    restart: unless-stopped
    working_dir: /var/www/laravel-shopify-app
    volumes:
      - ./:/var/www/laravel-shopify-app
    networks:
      - app-network
      - queue-network
      - db-network

  db1:
    image: mysql:5.7
    container_name: shopify-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - .docker/data/db:/var/lib/mysql/
    
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${ADMINER_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network



  nginx:
    image: nginx:alpine
    container_name: shopify-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/laravel-shopify-app
      - .docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

  npm:  
    image: node:18-alpine
    working_dir: /var/www/laravel-shopify-app
    volumes: 
      - ./:/var/www/laravel-shopify-app

  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - .docker/data/redis:/data
    restart: always
    networks:
      - queue-network
networks:
  app-network:
    driver: bridge
  queue-network:
    driver: bridge
  db-network:
    driver: bridge